### ISSUE TITLE
Emulating the CDJ on-air message from a non Pioneer mixer

### ISSUE THREAD

**Issue by GuyHarwood** [Deep-Symmetry/beat-link#32]
I would like to write a utility that could tell a CDJ 2000 Nexus / nxs2 that it is now 'on air' from a non pioneer nexus mixer.  

For example - when a MIDI message is received from my Xone 96 indicating that the channel fader is above zero, send a message to the relevant CDJ telling it to change the jog lights to red.

I notice there is an [interface](https://github.com/Deep-Symmetry/beat-link/blob/master/src/main/java/org/deepsymmetry/beatlink/OnAirListener.java) that can handle these type of events.  

A question to those that are familiar with the Pro DJ link protocol and capabilities of beat-link....

 is it feasible / possible to do this with beat-link or beat-link-trigger?

**Comment by brunchboy** [comment]
Yes, this should be possible. Once you have the `VirtualCdj` started and talking to your players, you can use its [`sendOnAirCommand`](https://deepsymmetry.org/beatlink/apidocs/org/deepsymmetry/beatlink/VirtualCdj.html#sendOnAirCommand-java.util.Set-) method to send a packet telling the players which channels are currently on the air. Since you have no nexus mixer on the network, they should remain in that state until you send another such message.

If you are looking to write the code inside the framework of beat-link-trigger, to save you the trouble of writing code to configure and start the various beat link components, the closest example to follow is probably [this one from the wiki](https://github.com/Deep-Symmetry/beat-link-trigger/wiki/Example:-Start-Player-3-when-another-Player-starts).

The best place to ask for guidance on this would be in the [Gitter chat](https://gitter.im/brunchboy/beat-link-trigger). People may be able to offer you more pointers or help you overcome hurdles there. If you do get this working, I’d really appreciate it if you could share your code on the Wiki.

**Comment by GuyHarwood** [comment]
Thanks for the info, this sounds promising.

I’m more than happy to share the code 👍🏼

**Comment by brunchboy** [comment]
Did you have any luck with this? I’d like to close the issue.

**Comment by GuyHarwood** [comment]
No, didn't make much progress

**Comment by brunchboy** [comment]
Can you share the MIDI messages that will be sent? I might be able to throw together some sample code for you to try.

**Comment by GuyHarwood** [comment]
that would be great - https://www.allen-heath.com/media/X96_MIDI-Control-Overview.pdf

Page 2 onward gives you all the detail on midi info sent from the faders

the biggest hurdle for me was the java environment/tooling, as i'm predominantly a C# & Typescript dev

**Comment by brunchboy** [comment]
Cool, thanks. I will probably do it as a configuration file for [Beat Link Trigger](https://github.com/Deep-Symmetry/beat-link-trigger) so that can do all the heavy lifting of managing lifecycles and providing a user interface.

**Comment by GuyHarwood** [comment]
Appreciate you taking this on 🏆

**Comment by brunchboy** [comment]
Hey, @GuyHarwood I just wanted to let you know I haven’t forgotten this, and I even just learned that my nexus 2000 mixer sends similar MIDI events as you adjust its controls, so I can use that to help validate a solution. But I have been shelled the last few weeks kicking off a new project, so I don’t know when I will have a chance to play with this.

However, it just occurred to me that my new project  might let you do this yourself! Have you ever played with [Pure Data](https://puredata.info) or [Max](https://cycling74.com)? They are graphical data flow environments that let you wire up crazy MIDI and audio/video integrations without traditional programming, and my new project lets them communicate with Pioneer players by bridging them using the Open Sound Control protocol. It already supports the On-Air messages that you need to do what you want. So if you have some time to experiment, you could build a patch that translates the mixer MIDI to the OSC message that would tell the players to do what you want. Open Beat Control is here: https://github.com/Deep-Symmetry/open-beat-control

**Comment by brunchboy** [comment]
Ok, even if there is a way to do this with Pure Data and Open Beat Control, it is still a very interesting integration example for Beat Link Trigger, so I am working on implementing that. I think I have the basic approach worked out enough to test with my own MIDI hardware tonight, but there are some questions that would benefit from details from @GuyHarwood if you have a chance.

First, for my basic approach, I want to make the notion of “on air” behave like it does in the DJM, in other words both the channel and the cross-fader need to be a little away from zero in order for that channel to be considered on the air. The threshold will be configurable through a labeled constant in the script I am writing. Does this sound good?

Secondly, I am going to assume that channels 1 and 2 are normally on the left side of the crossfader, and 3 and 4 are normally on the right, is that correct? Again, this will be configurable in the script if the mixer is itself configurable, but I want the defaults to match the way the mixer ships.

One thing I do not know is whether the MIDI values for the crossfader increase or decrease as you move it from left to right. Could you use MIDI Monitor (or some equivalent program) to test that out for me?

Also, what is the name of the MIDI device that appears when the mixer is connected? I need some unique string by which the script can open it for input.

**Comment by brunchboy** [comment]
Ok, @GuyHarwood here is a [Beat Link Trigger](https://github.com/Deep-Symmetry/beat-link-trigger#beat-link-trigger) show that I think will work for you. I have only tested it with a simulated Xone:96 mixer that I set up as a Max patch, and you will need to edit the Global Setup Expression and change the value assigned to `mixer-device-name` on line 13 to be the actual MIDI input that the mixer sends its messages to on your computer. Please let me know what value you actually need to use, and how this works for you! Once I get some feedback, I will write up some general instructions, and include it as an example in the Beat Link Trigger User Guide.

[XoneOnAir.bls.zip](https://github.com/Deep-Symmetry/beat-link/files/3844229/XoneOnAir.bls.zip)

You will need to unzip the above before opening it in Beat Link Trigger. (Although the show files are already compressed, GitHub requires it to be zipped again to attach.)

**Comment by mattpstv** [comment]
Sorry to jump in here but I've been following @GuyHarwood questions about using the Allen & Heath xone:96 with beat-link trigger very closely (I sold my djm-900nxs2 a while back and got the xone:96). Figured I could offer some secondary insight here....

1) " I want to make the notion of “on air” behave like it does in the DJM, in other words both the channel and the cross-fader need to be a little away from zero in order for that channel to be considered on the air." 
I'm excited for this development. The xone96 uses an amazing Innofader Mini as their stock crossfader. Along with being about the best crossfader modern tech has to offer, A&H designed the 96 so that a user can open the front of the mixer and adjust the fader cut themselves ...and it is SHARP and amazing for scratching. This might be relevant to how you design the on air feature. Another thought, my personal preference is to have ch1 and ch4 be turntables, ch2 and 3 (center two) be for cdjs, and use ch A/5 for my DJS-1000 sampler and B/6 for either another sampler or a drum machine or whatever line-ready gear someone brings over. My point is that I leave the corssfader active only for ch1 and ch4 and usually ch2 and 3 are either set to crossfader not-active OR I set them to the ch4 crossfader (ch1: only when closed crossfader on left, ch2, ch3, ch4 when fader closed on the right . The crossfader doesn't effect chA/5 and chB/6.

**Comment by mattpstv** [comment]
"what is the name of the MIDI device that appears when the mixer is connected? I need some unique string by which the script can open it for input.' 

XONE 96 USB 1 (or 2) depending on which usb B jack you use (according to Audio MIDI setup. There's also a MIDI 5-Pin DIN that A&H documentation sometimes lists as "MIDI Out 1 x 5-Pin DIN" but other times as an "I/O" Midi.  ("XONE 96 1" shows up as the Port in MacOS Midi setup)

**Comment by brunchboy** [comment]
Please don’t apologize, @mattpstv your input is always welcome, and the purpose of this issue is to brainstorm ideas! Have you taken a look at the code yet, or tried the show with your mixer? From what you say in your second comment, changing the string in line 13 from `"Max 1"` to `"XONE"` and saving the Global Setup expression should make it start working.

Also, I noticed in the picture of the mixer in the MIDI manual that was cited in this discussion that you can assign channels 1-4 to either or neither side of the cross-fader, just like the channels on my DJM, so I wrote my code to support that. If you look at the top of the Shared Functions code in the show, you will see where sets of channel numbers get assigned to either side. Just edit those sets as appropriate for your setup.

I’d love to hear results from this so I can tweak it or write it up for inclusion in the User Guide!

**Comment by brunchboy** [comment]
(Also, assuming your eventual goal with this is to have something running on a Pi that does it for you on stage, you can create a Pure Data patch that takes the MIDI from the mixer and converts it to OSC messages you send to Open Beat Control to adjust the on-air lights. Or, your Pi may have plenty of memory to run an X server and Beat Link Trigger itself with this show.)

**Comment by brunchboy** [comment]
Ok, I have sketched out the user guide entry, you can find it [here](https://blt-guide.deepsymmetry.org/beat-link-trigger/integration#xone-on-air). It is easier to download the show file from there, and I have fixed the MIDI port name based on what @mattpstv reported. Can’t wait to hear how this is working for you two!

**Comment by GuyHarwood** [comment]
hey @brunchboy looks like you have been busy!  this sounds quality, will give it a shot today hopefully.

to answer your questions...

Threshold config sounds good, i can play around with the parameter in the script as you suggest.
Crossfader - i never use mine, but again, would be good to make it configurable, as i typically have my CDJs on channels 2 & 3.  

The MIDI device name - not sure, but it comes up as a USB Device like `XONE 96 USB 1` or `XONE 96 UBS 2` depending on which sound card i use.

Will report back asap.  Thanks again :)

**Comment by GuyHarwood** [comment]
@brunchboy MIDI Monitor output log attached.
Device comes up as `XONE 96 1`
[Xone Midi output log.zip](https://github.com/Deep-Symmetry/beat-link/files/3846583/Xone.Midi.output.log.zip)

**Comment by GuyHarwood** [comment]
When i set `mixer-device-name` to `XONE 96 1` and click update i get an exception...
```
Syntax error compiling at (22:7)
Cause: No such namespace: seesaw
You may wish to check log file for detailed stack trace
```

Do i need some libs installed on my mac mini i wonder?

**Comment by brunchboy** [comment]
Thank you for trying this! What do you see when you look at Help:About? It sounds like you may be running an older (released) version of BLT. Possibly in my volume of comments last night you did not see that this show requires some features present only in the latest preview build?

**Comment by GuyHarwood** [comment]
i downloaded the latest - 0.5.6, will search for a preview version now...

**Comment by brunchboy** [comment]
(I apologize for the extra work that entails, it means you need to have your own Java runtime installed, and run the Beat Link Trigger jar from a command line, but I can’t spend the hours of building native installer bundles except when a release is final and ready, and though the next release is near, I am still waiting for feedback from a variety of people to finish it off.)

**Comment by GuyHarwood** [comment]
@brunchboy was just about to ask if i needed to build source or use a jar :)

will grab the bits and report back..

**Comment by brunchboy** [comment]
Great, thanks! 😄  You should be able to find the 0.5.5 preview jar in the list of downloadables at the top of the Releases page: https://github.com/Deep-Symmetry/beat-link-trigger/releases/download/v0.5.4/beat-link-trigger-0.5.5-PREVIEW.jar

**Comment by brunchboy** [comment]
> __Oops!__ I just saw another browser window in which this comment from ten hours ago never got submitted. It may have helped clarify the need for the preview release:

Cool, I just confirmed that the show does properly send Channels On Air packets and affect the CDJs when I slide my simulated Xone:96 faders around in Max/MSP. So as long as I interpreted the MIDI chart properly and built my simulation to accurately reflect the real mixer (and assuming you edit the mixer MIDI name in the Global Setup Expression as described above, and are running the current preview of Beat Link Trigger) it should really work.

> I need to prepare for and head in to work, so I will be incommunicado for an hour or two, but I am hopeful we are close and with a few tweaks (such as perhaps swapping the orientation of the cross fader once I look at your MIDI Monitor log) it will work well.

**Comment by GuyHarwood** [comment]
we're in business....
👀 
[Youtube video](https://www.youtube.com/watch?v=NmY6KcyG27Y)

It only works on Channel 1 though, but i can figure that out via the code after work.
I'm sending beer tokens your way when this is done @brunchboy 🍺

**Comment by brunchboy** [comment]
🎉 That’s awesome! Thanks for sharing the video.

Please let me know what you ended up needing to tweak in the code. It may also be that the other player is not configured to display on-air state, I believe that is something you can configure via rekordbox device settings. I can also show you a snippet of code to add that will log the channels that are being set to on-air upon the receipt of relevant MIDI messages, that might help with troubleshooting.

In any case, if you haven’t already (and since you talked about renaming the MIDI port, you likely haven’t) I would suggest starting from the version of the show that is embedded in the preview User Guide (in the Integrations section), as it has a few tweaks beyond setting the port name to “XONE”. Mostly small typo fixes, but might as well start from my best version.

**Comment by brunchboy** [comment]
@GuyHarwood I see some inconsistencies between the MIDI Monitor log you sent me and the Xone:96 MIDI documentation you sent earlier. According to the documentation, the channel fader for channel 1 should be using CC number 0, and in your log, it is CC number 1 that is changing.

Also, according to the documentation, the cross fader should be CC number 5, and in your log it is CC number 4 that is changing. We might want to look at logs for all the channel faders, in order, and then the cross-fader, and ask for clarification from Allen & Heath.

**Comment by GuyHarwood** [comment]
@brunchboy it was channel fader 2 that i was moving up and down. 
i will redo the MIDI monitor log, just to double check everything and provide logs for each channel.

code wise - i only needed to change the mixer device name.

will have a play around tonight with the version you suggest to download

**Comment by brunchboy** [comment]
Oh, duh, right, you did indeed report that you were moving channel 2 up and down. So that is consistent with the documentation. It is looking like the only discrepancy, then, is that the cross-fader is CC 4 rather than CC 5. Which is certainly plausible, as things stand in their documentation, CC 4 is unused, which struck me as strange from the outset. I think that is just a misprint in their MIDI documentation. I will update the show in the User Guide to reflect what you found in your capture, and publish a new preview build.

**Comment by mattpstv** [comment]
The first thing that appeared in my FB feed today was @GuyHarwood video's in the A&H xone FB group. The best comment so far: "witchcraft".  I've really only used the midi out functionality of the xones to trigger individual samples as well as start sequences on my DJS-1000 (via 5 din midi out of the xone), but  just seeing a visual of the 'on air' trigger has got my brain fired up.

**Comment by brunchboy** [comment]
That’s delightful! I had been wondering how I could make more Xone users aware of this development once it is ready. 😀

**Comment by GuyHarwood** [comment]
yeah i put a link up to your github page too so peeps can have a look through your other stuff :)

so i now have both CDJ jogs turning red when i lift channels 1 & 2 respectively on the Xone 96.
Now i just need to configure mixer channels 2 & 3 to be mapped to CDJ 1 & 2 respectively.  I don't see anything in the code or integration examples that allows me to modify that.  is it hard coded?

**Comment by brunchboy** [comment]
If you scroll down to the Shared Functions section of https://blt-guide.deepsymmetry.org/beat-link-trigger/integration#xone-on-air you will see the first two callouts are where you assign channel numbers to sides of the cross-fader. Just adjust the numbers which appear inside the set constants (`#{ … }`).

**Comment by brunchboy** [comment]
(And you edit the Shared Functions using the Track menu in the show, the same way you did with the Global Setup expression.)

**Comment by brunchboy** [comment]
Oh, wait, misread you! Hold on.

**Comment by brunchboy** [comment]
What I would recommend you do instead is change the # that your CDJs display. Is there a reason you are unwilling to do that? I like my CDJ to display the channel number it is attached to on the mixer.

**Comment by brunchboy** [comment]
(And once you do that, the code will just work as it is already configured.)

**Comment by GuyHarwood** [comment]
good call, never thought of that :)

**Comment by brunchboy** [comment]
Here are some instructions from the Pioneer forum about assigning player channel numbers:

* Power on your CDJ
* Press and hold the "MENU" button on the top (This enters the Utility mode)
* Use the control knob to scroll down through the list until you reach "Player No."
* Press down on the knob to select it
* Scroll through your available channels (Auto, 1, 2, 3, 4)
* Press down on the knob to select your desired channel
* Press the "MENU" button again to exit the Utility setting

Note: It may be necessary to wait a few seconds for the "Auto" selection assigns your player number before you can edit it. You must also have all LAN and USB connections removed in order to assign the player number.

**Comment by GuyHarwood** [comment]
yeah you have to remove network cable and any USBs, and then you can edit it.

Thanks for the guidance, all running with on-air 🔈 🏆

**Comment by brunchboy** [comment]
Most excellent! 🎉  One (hopefully small) request: Even though you don’t use your cross-fader, could you test whether my code is handling it correctly? As things are configured, when you move it hard right, only channels 1 and 2 should be on-air, and hard left, only channels 3 and 4 should be on air (as long as their channel faders are up).

**Comment by GuyHarwood** [comment]
Crossfader isn't working, im on preview .55 

can i modify this myself? as i didn't catch anything in the docs or code that suggested i could switch to CC4?

**Comment by brunchboy** [comment]
Several questions there. Let’s get to the most important, though: Yes, check the code of the `xone-midi-received` function in the Shared Functions. There is a line that in my earlier versions was:

```clojure
5 :cross-fader
```

In a more recent version of the show (which I embedded in the user guide of a more recent preview build) I changed that to:

```clojure
4 :cross-fader
```

You can either start with the version of the show that is in the user guide on the Web right now, or in the latest preview build, or you can just change that 5 to a 4 yourself.

Telling which preview build you have requires more than the version, because that is always (for example) `0.5.5-SNAPSHOT`. But the About also includes the Git hash and the build timestamp.

**Comment by GuyHarwood** [comment]
nice one @brunchboy, cross-fader working 💪 

next challenge for me is to get Ableton Link communicating with the CDJs, so i can have Traktor + Ableton + CDJs in sync.  Looks like you already nailed that one so i've got some reading to do 🤓

**Comment by brunchboy** [comment]
Excellent. So, just to confirm my understanding: The latest version, with CC 4 for the cross-fader is working, and the left/right assumptions I made seem to be correct? If so, I think I will close this issue and point people at the upcoming release of Beat Link Trigger. Have fun with your explorations of Carabiner/Ableton Link, and other places you might go!

**Comment by GuyHarwood** [comment]
yep, CC 4 for cross-fader.

Thanks for everything 🍺

**Comment by brunchboy** [comment]
My pleasure, thanks for the idea and help sorting out the details! If you’re in the UK, it will be getting a bit late, but when you have a chance please let the people in that Facebook thread know that for now they need to use the preview build if they want to try this, but I hope to finalize this release this weekend.
