### ISSUE TITLE
Thought you might like to know…

### ISSUE THREAD

**Issue by ben-xo** [Deep-Symmetry/beat-link#34]
…that I've used beat-link to create a Last.fm scrobbler for CDJs! (It now duely shows up under the "Used By" button at the top of the project)

Apologies that this is not reallt an "issue", I just don't know how else to get in touch. :)

**Comment by brunchboy** [comment]
Sweet, I love to hear things like that! You can also email james@deepsymmetry.org, or chat on the Beat Link Trigger [gitter channel](https://gitter.im/brunchboy/beat-link-trigger) (there isn’t one for Beat Link itself yet, because only recently are people starting to use it directly, which was always my intention, while Beat Link Trigger was supposed to just be a proof of concept).

**Comment by brunchboy** [comment]
It’s funny, your project shows up in the Used by menu, but the total count is still showing as 1 up there, I am assuming it is some sort of caching issue on GitHub’s end. And I remain sad that they haven’t yet started tracking Clojure/Leiningen projects that depend on it, so none of my own projects that use it, and for which I wrote it, are showing up as users. Ah well, maybe someday!

**Comment by ben-xo** [comment]
I reckon that's one of those figrues that will regenerate overnight (or maybe sometime at the end of the week) - we have a number of things which are cached in that sort of way at Last.fm!
